# Generated by Django 3.1.1 on 2020-09-07 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='stie_name',
            new_name='site_name',
        ),
    ]
